version: "3.7"
services:
  master:
    image: ansible/ansible:default
    container_name: master01
    hostname: master01
    volumes:
      - ansible_vol:/var/ans
  host:
    links:
      - master
    image: debian
    container_name: host01
    hostname: host01
    stdin_open: true
    tty: true
    volumes:
     - ansible_vol:/var/ans
  host02:
    links:
      - master
    image: centos:7
    container_name: host02
    hostname: host02
    stdin_open: true
    tty: true
    volumes:
     - ansible_vol:/var/ans
  host03:
    links:
      - master
    image: ubuntu
    container_name: host03
    hostname: host03
    stdin_open: true
    tty: true
    volumes:
     - ansible_vol:/var/ans
volumes:
  ansible_vol: