---
# WEB SERVER

- hosts: webserver
  vars_files: vars/main.yml

  tasks:
  - name: install apache and php last version
    apt:
      name:
        - apache2
        - php
        - php-mysql
      state: present
      update_cache: yes
    when: ansible_os_family == 'Debian'
    tags:
      - install
      - web

  - name: Give writable mode to http folder
    file:
      path: /var/www/html
      state: directory
      mode: '0755'
    tags:
      - deploiement
      - web

  - name: remove default index.html
    file:
      path: /var/www/html/index.html
      state: absent
    tags:
      - deploiement
      - web

  - name: upload web app source
    copy:
      src: app/
      dest: /var/www/html/
    tags:
      - deploiement
      - web

  - name: deploy php database config
    copy:
      src: "db-config.php"
      dest: "/var/www/html/db-config.php"
    tags:
      - deploiement
      - web
  
  - name: ensure apache service is start
    service:
      name: apache2
      state: started
      enabled: yes
    tags:
      - service
      - web

# DATABASE SERVER - Role install
- hosts: dbserver
  vars_files:
    - vars/main.yml
  name: installation du rôle mysql
  roles:
    - { role: vanessakovalsky.mysql }
  become: yes
  tasks: 
  - name: upload sql table config
    copy:
      src: "table.sql"
      dest: "/tmp/table.sql"
    tags:
      - deploiement
      - db

  - name: Allow external MySQL connexions 
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: "# bind-address"
    tags:
      - config
      - db

  - name : moving mysql home
    user:
      name: mysql
      home: /var/lib/mysql
    tags:
      - deploiement
      - db
  - name: add sql table to database
    mysql_db:
      name: '{{ mysql_dbname }}'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: '{{ mysql_root_username }}'
      login_password: '{{ mysql_root_password }}'
      state: import 
      target: /tmp/table.sql
    tags:
      - deploiement
      - db
